### ISSUE TITLE
After deploying, PAY WITH STRIPE button doesn't do anything, redirecting... popup doesn't appear

### ISSUE THREAD

**Issue by BVesenjak** [adrianhajdin/ecommerce_sanity_stripe#37]

**Comment by shivam-jha2712** [comment]
Have you solved the problem and if you have could you please Guide me I am having the same issue

**Comment by mysterymethod** [comment]
if solved please reply

**Comment by shivam-jha2712** [comment]
> if solved please reply

Yes, It has been solved by some other guy in the community. Btw Thanks for asking

**Comment by shivam-jha2712** [comment]
Could you please close it.

**Comment by TheKelvinT** [comment]
Hi Guys, do you know the solution to this issue? I am still facing it.. these are the errors after click 'pay with stripe' btn
![q13](https://user-images.githubusercontent.com/100819164/206712175-0ff92365-65c2-49e8-abb5-706fa01e2ae9.PNG)
